In [2]:
import pandas as pd
SFPD = pd.read_csv('SFPD_incidents.csv')
date = [int(i.split('/')[-1]) for i in SFPD['Date']]
SFPD['Year']=date
data = SFPD.loc[SFPD['Category'].isin(['PROSTITUTION'])]

We now want to convert our data so we have total amount of prostitution, vehicle theft, and total amount for each district.

In [87]:
SFPD

IncidntNum         Category  \
0         150060275     NON-CRIMINAL   
1         150098210          ROBBERY   
2         150098210          ASSAULT   
3         150098210  SECONDARY CODES   
4         150098226        VANDALISM   
5         150098232     NON-CRIMINAL   
6         150098248  SECONDARY CODES   
7         150098248        VANDALISM   
8         150098254         BURGLARY   
9         150098260    LARCENY/THEFT   
10        150098345    LARCENY/THEFT   
11        150098345    DRUG/NARCOTIC   
12        150098345    DRUG/NARCOTIC   
13        150098345         WARRANTS   
14        150098367          ROBBERY   
15        150098373    VEHICLE THEFT   
16        150098373     NON-CRIMINAL   
17        150098389         WARRANTS   
18        150098395    LARCENY/THEFT   
19        150098408   OTHER OFFENSES   
20        150098414          ROBBERY   
21        150098414          ROBBERY   
22        150098414          ASSAULT   
23        150098414          ASSAULT   
24        150098420          ROBBERY   
25        150098420          ASSAULT   
26        150098420      WEAPON LAWS   
27        150098436     NON-CRIMINAL   
28        150098442   OTHER OFFENSES   
29        150098458          ASSAULT   
...             ...              ...   
2023835   160228015          ASSAULT   
2023836   160236212          ASSAULT   
2023837   160314755          ASSAULT   
2023838   160321017          ASSAULT   
2023839   160380916          ASSAULT   
2023840   160412183          ASSAULT   
2023841   160454129          ASSAULT   
2023842   160558066          ASSAULT   
2023843   160580207          ASSAULT   
2023844   160598385          ASSAULT   
2023845   160600463          ASSAULT   
2023846   160650446          ASSAULT   
2023847   160673410          ASSAULT   
2023848   160698797          ASSAULT   
2023849   160757729          ASSAULT   
2023850   160774137          ASSAULT   
2023851   160778991          ASSAULT   
2023852   160843920          ASSAULT   
2023853   160857993    VEHICLE THEFT   
2023854   160875832          ASSAULT   
2023855   160907300          ASSAULT   
2023856   166271975     NON-CRIMINAL   
2023857   166280675     NON-CRIMINAL   
2023858   169004460            FRAUD   
2023859    90578136    VEHICLE THEFT   
2023860   981021761         WARRANTS   
2023861    81076498   MISSING PERSON   
2023862   961392021   MISSING PERSON   
2023863   961392021     NON-CRIMINAL   
2023864   990340112     NON-CRIMINAL   

                                          Descript  DayOfWeek        Date  \
0                                    LOST PROPERTY     Monday  01/19/2015   
1                            ROBBERY, BODILY FORCE     Sunday  02/01/2015   
2             AGGRAVATED ASSAULT WITH BODILY FORCE     Sunday  02/01/2015   
3                                DOMESTIC VIOLENCE     Sunday  02/01/2015   
4        MALICIOUS MISCHIEF, VANDALISM OF VEHICLES    Tuesday  01/27/2015   
5             AIDED CASE -PROPERTY FOR DESTRUCTION     Sunday  02/01/2015   
6                                DOMESTIC VIOLENCE   Saturday  01/31/2015   
7                    MALICIOUS MISCHIEF, VANDALISM   Saturday  01/31/2015   
8                BURGLARY OF STORE, UNLAWFUL ENTRY   Saturday  01/31/2015   
9                          PETTY THEFT SHOPLIFTING   Saturday  01/31/2015   
10                         PETTY THEFT SHOPLIFTING     Sunday  02/01/2015   
11                  POSSESSION OF METH-AMPHETAMINE     Sunday  02/01/2015   
12           POSSESSION OF NARCOTICS PARAPHERNALIA     Sunday  02/01/2015   
13                                  WARRANT ARREST     Sunday  02/01/2015   
14                     ROBBERY, ARMED WITH A KNIFE     Sunday  02/01/2015   
15                               STOLEN AUTOMOBILE     Sunday  02/01/2015   
16                                  FOUND PROPERTY     Sunday  02/01/2015   
17                 ENROUTE TO OUTSIDE JURISDICTION     Sunday  02/01/2015   
18                    PETTY THEFT FROM LOCKED AUTO     Sunday  02

In [3]:
a2003=SFPD[SFPD.Year==2003].loc[SFPD['Category'].isin(['PROSTITUTION'])]['PdDistrict'].value_counts()
b2003=SFPD[SFPD.Year==2003].loc[SFPD['Category'].isin(['VEHICLE THEFT'])]['PdDistrict'].value_counts()
c2003=SFPD[SFPD.Year==2003]['PdDistrict'].value_counts()
a2015=SFPD[SFPD.Year==2015].loc[SFPD['Category'].isin(['PROSTITUTION'])]['PdDistrict'].value_counts()
b2015=SFPD[SFPD.Year==2015].loc[SFPD['Category'].isin(['VEHICLE THEFT'])]['PdDistrict'].value_counts()
c2015=SFPD[SFPD.Year==2015]['PdDistrict'].value_counts()
    
    

Making our data

In [12]:
data_scatter2003=pd.DataFrame()
data_scatter2015=pd.DataFrame()

data_scatter2003['X']=a2003
data_scatter2015['X']=a2015
data_scatter2003['Y']=b2003
data_scatter2015['Y']=b2015
data_scatter2003['Z']=c2003
data_scatter2015['Z']=c2015
data_scatter2003['District']=data_scatter2003.index.values
data_scatter2015['District']=data_scatter2015.index.values

In [13]:
data_scatter2003.to_json('scatter2003.json', orient = "values")
data_scatter2015.to_json('scatter2015.json', orient = "values")

X     Y      Z    District
MISSION     713  2063  21163     MISSION
NORTHERN    581  1879  18975    NORTHERN
TENDERLOIN  527   371  12737  TENDERLOIN
CENTRAL      70  1193  13622     CENTRAL
SOUTHERN     18  1426  25692    SOUTHERN
RICHMOND     15  1081   7692    RICHMOND
BAYVIEW      11  2121  15739     BAYVIEW
TARAVAL      10  1665  11329     TARAVAL
INGLESIDE     5  2319  14008   INGLESIDE
PARK          2  1207   8219        PARK

Saving to JSON

In [108]:
a[:]

MISSION       469
NORTHERN      115
CENTRAL        37
TENDERLOIN     35
SOUTHERN       15
BAYVIEW        10
INGLESIDE       6
TARAVAL         3
RICHMOND        1
PARK            1
Name: PdDistrict, dtype: int64

We remove everything except prostitution and remove the the outliers.

In [2]:
data_lonlat = data[['X','Y']]
data_lonlat = data_lonlat.loc[data_lonlat['Y']<85]


In [15]:
data_lonlat.to_json('./coords.json',orient = 'values')

In [5]:
import numpy as np
X =  np.matrix([data_lonlat['X'],data_lonlat['Y']]).T

In [6]:
#Train KMeans model
from sklearn.cluster import KMeans
def trainKmeans(nClusters, X):
	# nClusters is number of clusters and X is a matrix of training. For geodata it should be X = np.matrix([Xcoords, Ycoords]).T
    KM = KMeans(nClusters)
    KM.fit(X)
    return KM

In [7]:
K2 = trainKmeans(2,X)

In [12]:
df=pd.DataFrame()
cf=pd.DataFrame()
for i in range(2,7):
    KM = trainKmeans(i,X)
    df["K%d"%i]=KM.labels_

In [16]:
df.to_json('./labels.json',orient = "values")

In [30]:
for i in range(2,7):
    KM = trainKmeans(i,X)
    cf = pd.DataFrame()
    cf['ccx']=KM.cluster_centers_[:, 0]
    cf['ccy']=KM.cluster_centers_[:, 1]
    cf.to_json('./center%d.json'%i, orient = "values")

[ 37.76000422  37.78739426]
[ 37.78742455  37.76134606  37.73890649]
[ 37.78742712  37.76144681  37.7585723   37.71881425]
[ 37.78765447  37.7614257   37.7585723   37.78553069  37.71881425]
[ 37.7876559   37.7617104   37.75868925  37.78553711  37.72757762
  37.71917352]
